name: Flutter CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select the branch to run de CI workflow"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug
